{{- if .Values.ui.service.enable }}
---
apiVersion: v1
kind: Service
metadata:
  name: gigo-ui-service
  labels:
    {{- include "ui.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ui.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  sessionAffinity: {{ .Values.ui.service.sessionAffinity }}
  ports:
    - name: "http"
      port: {{ .Values.ui.service.port }}
      targetPort: "http"
      protocol: TCP
  {{- if eq "LoadBalancer" .Values.ui.service.type }}
  {{- with .Values.ui.service.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
  {{- end }}
  {{- with .Values.ui.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . | quote }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "ui.selectorLabels" . | nindent 4 }}
{{- end }}
