# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

development_mode: false

ui:
  replicaCount: 1

  dnsPolicy: ClusterFirst
  dnsConfig: {}

  image:
    repository: gigodev/gigo-ui
    pullPolicy: Always
    tag: "latest"
    imagePullSecrets: []

  nodeSelector: {}
  tolerations: {}

  service:
    enable: false
    type: ClusterIP
    sessionAffinity: ClientIP
    externalTrafficPolicy: Cluster
    loadBalancerIP: ""
    annotations: {}
    port: 3000

  ingress:
    enable: false
    className: ""
    apiHost: "ui.gage.intranet"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/affinity-mode: persistent
      nginx.ingress.kubernetes.io/proxy-body-size: 100m
      nginx.ingress.kubernetes.io/session-cookie-expires: '172800'
      nginx.ingress.kubernetes.io/session-cookie-hash: sha1
      nginx.ingress.kubernetes.io/session-cookie-max-age: '172800'
      nginx.ingress.kubernetes.io/session-cookie-name: gigo-session-affinity
      nginx.ingress.kubernetes.io/ssl-redirect: 'false'
      nginx.ingress.kubernetes.io/websocket-services: gigo-ui-service
    tls:
      enable: false
      secretName: ""
      wildcardSecretName: ""

  certs:
    secrets: []

  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: gigo/component
                  operator: In
                  values:
                    - "ui"
            topologyKey: kubernetes.io/hostname
          weight: 1